### Assignment - 10 (NumPy)

In [2]:
# 1. Create a null vector of size 10
import numpy as np
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2.  How to find the memory size of an array
n=np.zeros((5,5))
print("%d bytes" % (n.size * n.itemsize))

200 bytes


In [6]:
# 3. Create a null vector of size 10 but the fifth value which is 1
x=np.zeros(10)
x
x[5]=1
x[6]=6
x


array([0., 0., 0., 0., 0., 1., 6., 0., 0., 0.])

In [10]:
# 4. Create a vector with values ranging from 15 to 45
x=np.arange(15,55)
x

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [14]:
# 5.Reverse a vector (The first element becomes last)
x=np.arange(13,20)
print("original array")
print(x)
print("\nReversing array")
x=x[::-1]
print(x)

original array
[13 14 15 16 17 18 19]

Reversing array
[19 18 17 16 15 14 13]


In [19]:
# 6. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
import numpy as np
print("Add")
print(np.add(2,4))
print("subtract")
print(np.subtract(2,4))
print("Multiply")
print(np.multiply(2,4))
print("divide")
print(np.divide(2,4))

Add
6
subtract
-2
Multiply
8
divide
0.5


In [23]:
# 7. Write a NumPy program to round elements of the array to the nearest integer.
import numpy as np
x=np.array([-.7,-1.5,-1.6,0.3,1.5,1.8,2.0])
print("original array")
print(x)
x=np.rint(x)
print("\nround element of the array to the nereasest integer")
print(x)

original array
[-0.7 -1.5 -1.6  0.3  1.5  1.8  2. ]

round element of the array to the nereasest integer
[-1. -2. -2.  0.  2.  2.  2.]


In [8]:
x=np.array([-.7,-1.5,-1.6,0.3,1.5,1.8,2.0])
x1=np.around(x)
x1

array([-1., -2., -2.,  0.,  2.,  2.,  2.])

In [26]:
# 8. Write a NumPy program to get the floor and ceiling values of the elements of a NumPy array
x=np.array([3.1,3.5,4.5,2.9,-3.1,-3.5,-5.9])
print("original array")
print(x)
x1=np.floor(x)
x2=np.ceil(x)
print("\nfloor:",x1)
print("\nceil:",x2)

original array
[ 3.1  3.5  4.5  2.9 -3.1 -3.5 -5.9]

floor: [ 3.  3.  4.  2. -4. -4. -6.]

ceil: [ 4.  4.  5.  3. -3. -3. -5.]


In [10]:
# 9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array
import numpy as np
x=np.array([[10,20],[30,40]])
print("original array")
print(x)
print(x.mean())

print("\nmean of each column")
print(x.mean(axis=1))

print("\nmean of each row")
print(x.mean(axis=0))


original array
[[10 20]
 [30 40]]
25.0

mean of each column
[15. 35.]

mean of each row
[20. 30.]


In [19]:
x=np.array([[[10,20],[30,40],[10,20],[30,40]]],ndmin=5)
np.ndim(x)



5

In [32]:
# 10. Write a NumPy program to convert angles from degrees to radians for all elements in a given array
x=np.array([-180.,-90.,90.,180.])
print("original array")
print(x)
r1=np.radians(x)
r2=np.deg2rad(x)
print(r1)
print(r2)

original array
[-180.  -90.   90.  180.]
[-3.14159265 -1.57079633  1.57079633  3.14159265]
[-3.14159265 -1.57079633  1.57079633  3.14159265]


##  11.What is the use of all and any function in numpy?
The any() function is used to test whether any array element along a given axis evaluates to True.

Returns single boolean unless axis is not None.

-syntax:-
 numpy.any(a, axis=None, out=None, keepdims = <no value>)

-The numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.
    
    -Syntax: numpy.all(array,
                    axis = None,
                    out = None,
                    keepdims = class numpy._globals._NoValue at 0x40ba726c)
 


In [22]:
x=np.array([1,2,3,4,5,6,0])
np.any(x)

True

In [25]:
x=np.array([1,2,3,4,5,6,False])
np.all(x)

False

In [41]:
# 12.Create a 3x3 matrix with values ranging from 0 to 8
# [[0 1 2]
# [3 4 5]
# [6 7 8]]

import numpy as np
x=np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
# 13.  How to reverse the columns of a 2D array?
# ([[2, 1, 0],
# [5, 4, 3],
# [8, 7, 6]])
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
print("original array")
print(x)
reversed_column=np.flip(x,axis=1)
print("\nreversed_colunm")
print(reversed_column)

original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

reversed_colunm
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [51]:
# 14.  How to reverse the rows of a 2D array?
# [[6, 7, 8],
# [3, 4, 5],
# [0, 1, 2]]

x=np.array([[0,1,2],[3,4,5],[6,7,8]])
print("original array")
print(x)

reversed_row=np.flip(x,axis=0)
print("\nreversed_row")
print(reversed_row)

original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

reversed_row
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [28]:
# 15. Find indices of non-zero elements from [1,2,0,0,4,0]
x=np.array([0,1,2,0,0,4,0])
print("original array")
print(x)
print("\nindiceses of non zero element")
result=np.where(x != 0)[0]
print(result)

original array
[0 1 2 0 0 4 0]

indiceses of non zero element
[1 2 5]


In [60]:
# 16.Write a NumPy program to compute the determinant of an array.
x=np.array([[10,20],[30,40]])
print("original array")
print(x)
result=np.linalg.det(x)
print("\nDeterminant of given array")
print(result)

original array
[[10 20]
 [30 40]]

Determinant of given array
-200.0000000000001


In [61]:
# 17. Write a NumPy program to compute the inverse of a given matrix
x=np.array([[10,20],[30,40]])
print("original array")
print(x)
result=np.linalg.inv(x)
print("\nInverse of the given matrix")
print(result)

original array
[[10 20]
 [30 40]]

Inverse of the given matrix
[[-0.2   0.1 ]
 [ 0.15 -0.05]]


In [65]:
# 18. Create a random vector of size 30 and find the mean value

x= np.random.random(30)
print("original array")
print(x)
result=x.mean()
result

original array
[0.05541143 0.83370438 0.93737095 0.50167817 0.9573896  0.59241837
 0.06291831 0.93755707 0.72802444 0.12032817 0.9353408  0.34556795
 0.5089886  0.17836232 0.22794872 0.13092345 0.46458925 0.98055494
 0.40029828 0.7248523  0.37067407 0.7751461  0.83798741 0.59867061
 0.01699319 0.72651595 0.20504151 0.14858382 0.76693643 0.9820164 ]


0.5350930995499306

In [32]:
# 19.. How to extract all numbers between a given range from a NumPy array?
x=np.arange(25)
result=np.where((x >= 1) & (x <= 10))
print(result)
#x


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)


In [36]:
# 20. . Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
print(x)

[[[0.74977381 0.86355728 0.8838535 ]
  [0.37663866 0.00427389 0.43772906]
  [0.85940786 0.43196337 0.69452314]]

 [[0.27398775 0.98822588 0.47456953]
  [0.42165748 0.91973257 0.75837837]
  [0.09890989 0.67288543 0.2746717 ]]

 [[0.81035396 0.22360827 0.3215976 ]
  [0.75167312 0.58994514 0.84710259]
  [0.03214654 0.36085302 0.52875412]]]


In [75]:
# 21. Create a 10x10 array with random values and find the minimum and maximum values
x= np.random.random((10,10))
print(x)
xmin,xmax=x.min(),x.max()
print("\nminimum and maximum value ")
print(xmin,xmax)

[[0.76055332 0.83328708 0.29355891 0.84679472 0.16312489 0.04128083
  0.49316958 0.59075524 0.75944857 0.2655041 ]
 [0.72914055 0.11250109 0.50020746 0.22063577 0.84959375 0.5724795
  0.28509971 0.12601421 0.73465143 0.82445446]
 [0.04714663 0.5931612  0.5050218  0.99623784 0.43996226 0.51556383
  0.54845372 0.63451678 0.82285623 0.24393444]
 [0.12363332 0.09599126 0.52750599 0.37996004 0.1343168  0.69718267
  0.34386085 0.53423154 0.82562147 0.97585409]
 [0.89118988 0.22725125 0.80930111 0.90978326 0.92562594 0.55728262
  0.82883588 0.08243277 0.52148148 0.3172785 ]
 [0.86000326 0.82482159 0.07132537 0.08563604 0.60156791 0.78763959
  0.43817268 0.25877105 0.73839293 0.28638644]
 [0.94837658 0.44149267 0.45741533 0.35006147 0.16840466 0.67096039
  0.33968645 0.4542874  0.44155557 0.29954544]
 [0.0045157  0.61457536 0.22453195 0.4242114  0.77011611 0.56742498
  0.95431088 0.60813064 0.92179207 0.95960643]
 [0.72232611 0.58645624 0.50865622 0.89350985 0.45703281 0.72099864
  0.47998287 

In [38]:
# 22. Create a 2d array with 1 on the border and 0 inside
x=np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
# 23. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x=np.diag([1,2,3,4])
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [46]:
# 24. Create a 3x3 identity matrix
x=np.identity(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
x=np.eye(4,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [84]:
# 25. Create a 8x8 matrix and fill it with a checkerboard pattern
# [[0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]]

print("checkbord pattern")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


checkbord pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [85]:
# 26. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x=np.dot(np.ones((5,3)),np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [87]:
x=np.random.random((5,3))
print("first array")
print(x)
y=np.random.random((3,2))
print("\nsecond array")
print(y)
z=np.dot(x,y)
print("\ndot product array")
print(z)

first array
[[0.20766893 0.89450743 0.95034234]
 [0.10384368 0.37080263 0.13087364]
 [0.22801862 0.02290082 0.84700773]
 [0.05379616 0.13784517 0.13293753]
 [0.18287888 0.63070115 0.33848692]]

second array
[[0.68612749 0.46204713]
 [0.9130364  0.47837521]
 [0.31326638 0.5164363 ]]

dot product array
[[1.25691551 1.01465429]
 [0.45080462 0.29295136]
 [0.44269817 0.55373607]
 [0.20441354 0.15945184]
 [0.80736791 0.56101739]]


In [88]:
# 27.Given a 1D array, negate all elements which are between 3 and 8, in place
x=np.arange(11)
x[(3<x) & (x <=8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [94]:
# 28. How to round away from zero a float array?
x=np.array([32.11, 51.5, 0.112])
print(x)
result=np.round(x)
print(result)

[32.11  51.5    0.112]
[32. 52.  0.]


In [98]:
# 29. How to find common values between the two arrays?
array1=np.array([10,20,30,40,50])
print("array1")
print(array1)
array2=np.array([10,30,50,60,70])
print("array2")
print(array2)
result=np.intersect1d(array1,array2)
print("\ncommon value")
print(result)

array1
[10 20 30 40 50]
array2
[10 30 50 60 70]

common value
[10 30 50]


In [102]:
# 30. Create a vector of size 10 with values ranging from 0 to 1, both excluded
x=np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [104]:
# 31.  Create a random vector of size 10 and sort it
x=np.random.random(10)
print("original array")
print(x)
x.sort()
print("\nsorted array")
print(x)

original array
[0.73305183 0.74696123 0.17630667 0.52427284 0.86687175 0.18928023
 0.59578169 0.54328942 0.42378203 0.01464964]

sorted array
[0.01464964 0.17630667 0.18928023 0.42378203 0.52427284 0.54328942
 0.59578169 0.73305183 0.74696123 0.86687175]


In [117]:
# 32. Create a 5x5 matrix with row values ranging from 0 to 4
# [[0. 1. 2. 3. 4.]
# [0. 1. 2. 3. 4.]
# [0. 1. 2. 3. 4.]
# [0. 1. 2. 3. 4.]
# [0. 1. 2. 3. 4.]]
x=np.zeros((5,5))
print("original array")
print(x)
x +=np.arange(5)
print("\nresult of row value")

print(x)

original array
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

result of row value
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [50]:
# 33.Consider two random arrays A and B, check if they are equal
x=np.random.randint(0,1,3)
print(x)
y=np.random.randint(0,1,3)
print(y)
z=np.allclose(x,y)
print(z)

[0 0 0]
[0 0 0]
True


In [128]:
# 34.Create a random vector of size 10 and replace the maximum value by 0
x=np.random.random(10)
print("original array")
print(x)
x[x.argmax()]=0
print("\nreplace the maximum value by 0")
print(x)

original array
[0.4921468  0.15298872 0.27687645 0.60727468 0.69379658 0.67586064
 0.09881232 0.36786762 0.62186391 0.04396414]

replace the maximum value by 0
[0.4921468  0.15298872 0.27687645 0.60727468 0.         0.67586064
 0.09881232 0.36786762 0.62186391 0.04396414]


In [188]:
# 35. How to find out multiple indices of an item?
array=np.random.randint(1,10,size=(2,2))
print("array\n",array)
for i,v in np.ndenumerate(array):
 print(i,v)

array
 [[1 3]
 [4 7]]
(0, 0) 1
(0, 1) 3
(1, 0) 4
(1, 1) 7


In [131]:
# 36. What is the equivalent of enumerate for NumPy arrays?
x=np.array([20,30,40,5,1])
print(x)
for i,v in np.ndenumerate(x):
    print(i,v)


[20 30 40  5  1]
(0,) 20
(1,) 30
(2,) 40
(3,) 5
(4,) 1


In [164]:
# 37.  How to sort an array by the nth column?
x=np.array([[9,2,3],[4,5,6],[7,0,5]])
print(x)
result=np.sort(x,axis=1)
print("\nsort column")
print(result)

[[9 2 3]
 [4 5 6]
 [7 0 5]]

sort column
[[2 3 9]
 [4 5 6]
 [0 5 7]]


In [148]:
# 38. How to swap two rows of an array?
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)
a[[0, 1]] = a[[1, 0]]
print("\nswap two rows of an array")
print(a)


[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]

swap two rows of an array
[[5 7 0]
 [4 3 1]
 [9 9 3]
 [8 2 4]]


In [154]:
# 39.  How to compute the mean of a NumPy array?
x=np.array([[2,4],[3,5]])
print(x)
print("mean of numpy array")
print(np.mean(x))

a=np.mean(x,axis=0)
print("\nmean of axis 0")
print(a)
b=np.mean(x,axis=1)
print("\nmean of axis 1")
print(b)

[[2 4]
 [3 5]]
mean of numpy array
3.5

mean of axis 0
[2.5 4.5]

mean of axis 1
[3. 4.]


In [158]:
# 40.How to compute the median of a NumPy array?
x=np.array([[2,5],[6,7]])
print(x)
print("median of numpy array")
print(np.median(x))
y=np.median(x,axis=0)
print("\nmedian of axis of 0")
print(y)
z=np.median(x,axis=1)
print("\nmedian of axis of 1")
print(z)

[[2 5]
 [6 7]]
median of numpy array
5.5

median of axis of 0
[4. 6.]

median of axis of 1
[3.5 6.5]


In [167]:
# 41. How to compute the standard deviation of a NumPy array?
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)
result=np.std(a)
print(result)


[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
2.92854723180093


In [172]:
# 42. How to compute the mode of a NumPy array?
from scipy.stats import mode
array1 = np.array([2,3,4,5,6,5,2,3,5,5,1,5,5,7,8])
print(array1)
mode = mode(array1)
print(mode)

[2 3 4 5 6 5 2 3 5 5 1 5 5 7 8]
ModeResult(mode=array([5]), count=array([6]))


In [52]:
# 43. How to print only 3 decimal places in a python NumPy array?

x=np.random.rand(2,2)
print(x)
print("\nthree decimal places value")
print(np.around(x,3))

[[0.52825894 0.46632905]
 [0.03501464 0.25005945]]

three decimal places value
[[0.528 0.466]
 [0.035 0.25 ]]


In [180]:
# 44. Write a NumPy program to compute the inverse of a given matrix
a = np.array([[[1,2],[3,4]]]) 
print(a)
result=np.linalg.inv(a)
print("\ninverse of given matrix")
print(result)

[[[1 2]
  [3 4]]]

inverse of given matrix
[[[-2.   1. ]
  [ 1.5 -0.5]]]


In [181]:
# 45.. Write a NumPy program to compute the covariance matrix of two given arrays
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [183]:
# 46. How to find the most frequent value in a NumPy array?
x = np.random.randint(0, 10, 30)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 3 2 6 1 5 1 4 5 7 1 3 9 1 3 0 5 7 0 8 1 9 6 5 7 8 2 9 4 9]
Most frequent value in the above array:
1


In [184]:
# 47. How to convert 1D array to 3D array?
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d = np.reshape(arr, (2, 2, 3))
print('3D Numpy array:')
print(arr_3d)

3D Numpy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
# 48. How to convert 4D array to 2D array?
arr=np.random.randint(10,20,size=(2,2,3,2),dtype=int)
print("array",arr)
arr =arr.reshape(4,6)
print("\nconverted 2D array\n",arr) 

array [[[[12 17]
   [16 16]
   [17 14]]

  [[15 17]
   [14 18]
   [17 11]]

  [[18 14]
   [17 16]
   [18 14]]]


 [[[11 16]
   [10 19]
   [11 12]]

  [[19 10]
   [14 12]
   [12 16]]

  [[17 11]
   [11 15]
   [13 15]]]


 [[[19 10]
   [11 13]
   [14 15]]

  [[11 15]
   [13 12]
   [19 16]]

  [[12 17]
   [10 14]
   [13 10]]]]


ValueError: cannot reshape array of size 54 into shape (4,6)

In [186]:
# 49. Create a Numpy array filled with all zeros
arr1=np.zeros([4,8])
print(arr1)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [187]:
# 50. Find the number of rows and columns of a given matrix using NumPy
arr1=np.array([[1,2,3,4,4],[3,4,5,7,8],[8,7,4,3,1]])
print("array : \n",arr1)
print("Number of rows : ",arr1.shape[0])
print("Number of column : ",arr1.shape[1])

array : 
 [[1 2 3 4 4]
 [3 4 5 7 8]
 [8 7 4 3 1]]
Number of rows :  3
Number of column :  5
